// Counselor Actions types
export const SET_COUNSELOR = 'SET_COUNSELOR';

export const SET_TOKEN = 'SET_TOKEN';

export const SET_COUNSELOR_EDITED = 'SET_COUNSELOR_EDITED';

// Application Actions types
export const IS_LOADING = 'IS_LOADING';

export const IS_NOT_LOADING = 'IS_NOT_LOADING';

// Report Actions types
export const SET_STOCKFOODOBSERVATION = 'SET_STOCKFOODOBSERVATION';

export const SET_STOCKFOODREPORT_POSITIVE = 'SET_STOCKFOODREPORT_POSITIVE';

export const SET_STOCKFOODREPORT_NEGATIVE = 'SET_STOCKFOODREPORT_NEGATIVE';

export const SET_REFECTORYOBSERVATION = 'SET_REFECTORYOBSERVATION';

export const SET_REFECTORYREPORT_NEGATIVE = 'SET_REFECTORYREPORT_NEGATIVE';

export const SET_REFECTORYREPORT_POSITIVE = 'SET_REFECTORYREPORT_POSITIVE';

export const SET_KITCHENOBSERVATION = 'SET_KITCHENOBSERVATION';

export const SET_KITCHENREPORT_POSITIVE = 'SET_KITCHENREPORT_POSITIVE';

export const SET_KITCHENREPORT_NEGATIVE = 'SET_KITCHENREPORT_NEGATIVE';

export const SET_FOODQUALITYOBSERVATION = 'SET_FOODQUALITYOBSERVATION';

export const SET_FOODQUALITYREPORT_POSITIVE = 'SET_FOODQUALITYREPORT_POSITIVE';

export const SET_FOODQUALITYREPORT_NEGATIVE = 'SET_FOODQUALITYREPORT_NEGATIVE';

export const SET_DOCOBSERVATION = 'SET_DOCOBSERVATION';

export const SET_DOCREPORT_POSITIVE = 'SET_DOCREPORT_POSITIVE';

export const SET_DOCREPORT_NEGATIVE = 'SET_DOCREPORT_NEGATIVE';

export const SET_REPORTOBSERVATION = 'SET_REPORTOBSERVATION';

export const SET_STATUSFOODQUALITY = 'SET_STATUSFOODQUALITY';

export const SET_SCHOOLSURROUNDINGSOBSERVATION = 'SET_SCHOOLSURROUNDINGSOBSERVATION';

export const SET_SCHOOLSURROUNDINGSREPORT_NEGATIVE = 'SET_SCHOOLSURROUNDINGSREPORT_NEGATIVE';

export const SET_SCHOOLSURROUNDINGSREPORT_POSITIVE = 'SET_SCHOOLSURROUNDINGSREPORT_POSITIVE';

// School Action types
export const SET_SCHOOL_INFO = 'SET_SCHOOL_INFO';

// List Actions types
export const SET_LIST_COUNSELOR_GROUP = 'SET_LIST_COUNSELOR_GROUP';

export const RESET_LIST = 'RESET_LIST';
