export const SET_COUNSELOR = 'SET_COUNSELOR';

export const CREATE_COUNSELOR = 'CREATE_COUNSELOR';

export const CREATE_SUCCESS = 'CREATE_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const  LOGIN_FAIL = 'LOGIN_FAIL'

export const  MODIFY_CPF = 'MODIFY_CPF'

export const  MODIFY_PASSWORD = 'MODIFY_PASSWORD'

export const  LOADING = 'LOADING'
