// Counselor Actions types
export const SET_COUNSELOR = 'SET_COUNSELOR';

export const SET_TOKEN = 'SET_TOKEN';

export const SET_COUNSELOR_EDITED = 'SET_COUNSELOR_EDITED';

// Counselor Manage
export const SET_COUNSELOR_ACCEPTED = 'SET_COUNSELOR_ACCEPTED';

// Application Actions types
export const IS_LOADING = 'IS_LOADING';

export const IS_NOT_LOADING = 'IS_NOT_LOADING';

// Report Actions types
export const SET_STOCKFOODOBSERVATION = 'SET_STOCKFOODOBSERVATION';

export const SET_STOCKFOODREPORT_POSITIVE = 'SET_STOCKFOODREPORT_POSITIVE';

export const SET_STOCKFOODREPORT_NEGATIVE = 'SET_STOCKFOODREPORT_NEGATIVE';

export const SET_REFECTORYOBSERVATION = 'SET_REFECTORYOBSERVATION';

export const SET_REFECTORYREPORT_NEGATIVE = 'SET_REFECTORYREPORT_NEGATIVE';

export const SET_REFECTORYREPORT_POSITIVE = 'SET_REFECTORYREPORT_POSITIVE';

export const SET_KITCHENOBSERVATION = 'SET_KITCHENOBSERVATION';

export const SET_KITCHENREPORT_POSITIVE = 'SET_KITCHENREPORT_POSITIVE';

export const SET_KITCHENREPORT_NEGATIVE = 'SET_KITCHENREPORT_NEGATIVE';

export const SET_FOODHANDLEROBSERVATION = 'SET_FOODHANDLEROBSERVATION';

export const SET_FOODHANDLERREPORT_POSITIVE = 'SET_FOODHANDLERREPORT_POSITIVE';

export const SET_FOODHANDLERREPORT_NEGATIVE = 'SET_FOODHANDLERREPORT_NEGATIVE';

export const SET_FOODPREPARATIONOBSERVATION = 'SET_FOODPREPARATIONOBSERVATION';

export const SET_FOODPREPARATIONREPORT_POSITIVE = 'SET_FOODPREPARATIONREPORT_POSITIVE';

export const SET_FOODPREPARATIONREPORT_NEGATIVE = 'SET_FOODPREPARATIONREPORT_NEGATIVE';

export const SET_WATERSEWERSUPPLYOBSERVATION = 'SET_WATERSEWERSUPPLYOBSERVATION';

export const SET_WATERSEWERSUPPLYREPORT_POSITIVE = 'SET_WATERSEWERSUPPLYREPORT_POSITIVE';

export const SET_WATERSEWERSUPPLYREPORT_NEGATIVE = 'SET_WATERSEWERSUPPLYREPORT_NEGATIVE';

export const SET_FOODQUALITYOBSERVATION = 'SET_FOODQUALITYOBSERVATION';

export const SET_ACCEPTEDMENU = 'SET_ACCEPTEDMENU';

export const SET_REFUSEDMENU = 'SET_REFUSEDMENU';

export const SET_FOODQUALITYREPORT_POSITIVE = 'SET_FOODQUALITYREPORT_POSITIVE';

export const SET_FOODQUALITYREPORT_NEGATIVE = 'SET_FOODQUALITYREPORT_NEGATIVE';

export const SET_DOCOBSERVATION = 'SET_DOCOBSERVATION';

export const SET_DOCREPORT_POSITIVE = 'SET_DOCREPORT_POSITIVE';

export const SET_DOCREPORT_NEGATIVE = 'SET_DOCREPORT_NEGATIVE';

export const SET_REPORTOBSERVATION = 'SET_REPORTOBSERVATION';

export const SET_STATUSFOODQUALITY = 'SET_STATUSFOODQUALITY';

export const SET_STATUSWATERSEWERSUPPLY = 'SET_STATUSWATERSEWERSUPPLY';

export const SET_STATUSDOC = 'SET_STATUSDOC';

export const SET_STATUSKITCHEN = 'SET_STATUSKITCHEN';

export const SET_STATUSREFECTORY = 'SET_STATUSREFECTORY';

export const SET_STATUSFOODPREPARATION = 'SET_STATUSFOODPREPARATION';

export const SET_STATUSFOODHANDLER = 'SET_STATUSFOODHANDLER';

export const SET_STATUSREPORTOBSERVATION = 'SET_STATUSREPORTOBSERVATION';

export const SET_STATUSSCHOOLSURROUNDINGS = 'SET_STATUSSCHOOLSURROUNDINGS';

export const SET_STATUSSTOCKFOOD = 'SET_STATUSSTOCKFOOD';

export const SET_SCHOOLSURROUNDINGSOBSERVATION = 'SET_SCHOOLSURROUNDINGSOBSERVATION';

export const SET_SCHOOLSURROUNDINGSREPORT_NEGATIVE = 'SET_SCHOOLSURROUNDINGSREPORT_NEGATIVE';

export const SET_SCHOOLSURROUNDINGSREPORT_POSITIVE = 'SET_SCHOOLSURROUNDINGSREPORT_POSITIVE';

// School Action types
export const SET_SCHOOL_INFO = 'SET_SCHOOL_INFO';

export const SET_SCHOOL_CITY = 'SET_SCHOOL_CITY';

export const SET_SCHOOL_UF = 'SET_SCHOOL_UF';

// List Actions types
export const SET_LIST_COUNSELOR_GROUP = 'SET_LIST_COUNSELOR_GROUP';

export const RESET_LIST = 'RESET_LIST';

export const SET_NEW_LISTS = 'SET_NEW_LISTS';

export const SET_PENDING_SCHEDULE_LIST = 'SET_PENDING_SCHEDULE_LIST';

export const SET_EXPIRED_SCHEDULE_LIST = 'SET_EXPIRED_SCHEDULE_LIST';

export const SET_ALREADY_INPECTIONED_SCHEDULE_LIST = 'SET_ALREADY_INPECTIONED_SCHEDULE_LIST';

// Scheduling Action types

export const SET_SCHEDULE_INFO = 'SET_SCHEDULE_INFO';
