export const GET_VISIT_SCHEDULE_CONTENT_ERROR = 'GET_VISIT_SCHEDULE_CONTENT_ERROR';

export const GET_VISIT_SCHEDULE_POST_LIST_ERROR = 'GET_VISIT_SCHEDULE_POST_LIST_ERROR';

export const GET_CURRENT_SCHEDULE_ERROR = 'GET_CURRENT_SCHEDULE_ERROR';

export const UPDATE_CURRENT_SCHEDULE_ERROR = 'UPDATE_CURRENT_SCHEDULE_ERROR';

export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const PROFILE_LOGIN_ERROR = 'PROFILE_LOGIN_ERROR';

export const GROUP_LOGIN_ERROR = 'GROUP_LOGIN_ERROR';

export const GET_COUNSELORS_GROUP_LINKS_ERROR = 'GET_COUNSELORS_GROUP_LINKS_ERROR';

export const GET_COUNSELORS_FROM_CAE_ACCOUNT_ERROR = 'GET_COUNSELORS_FROM_CAE_ACCOUNT_ERROR';

export const GET_COUNSELORS_FROM_CAE_PROFILE_ERROR = 'GET_COUNSELORS_FROM_CAE_PROFILE_ERROR';

export const GET_GROUP_ERROR = 'GET_GROUP_ERROR';
export const EDIT_ACCOUNT_ERROR = 'EDIT_ACCOUNT_ERROR';

export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR';
export const AFTER_INPECTION_POST_ERROR = 'AFTER_INPECTION_POST_ERROR';

export const BEFORE_INPECTION_POST_ERROR = 'BEFORE_INPECTION_POST_ERROR';
