export const GET_VISIT_SCHEDULE_CONTENT_ERROR = 'GET_VISIT_SCHEDULE_CONTENT_ERROR';

export const GET_VISIT_SCHEDULE_POST_LIST_ERROR = 'GET_VISIT_SCHEDULE_POST_LIST_ERROR';

export const GET_CURRENT_SCHEDULE_ERROR = 'GET_CURRENT_SCHEDULE_ERROR';

export const UPDATE_CURRENT_SCHEDULE_ERROR = 'UPDATE_CURRENT_SCHEDULE_ERROR';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const PROFILE_LOGIN_ERROR = 'PROFILE_LOGIN_ERROR';

export const GROUP_LOGIN_ERROR = 'GROUP_LOGIN_ERROR';
<<<<<<< Updated upstream
=======

export const EDIT_ACCOUNT_ERROR = 'EDIT_ACCOUNT_ERROR';

export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR';

export const GET_GROUP_ERROR = 'GET_GROUP_ERROR';

export const GET_GROUP_EACH_COUNSELOR_LINK = 'GET_GROUP_EACH_COUNSELOR_LINK';

export const GET_EACH_COUNSELOR_FROM_CAE = 'GET_EACH_COUNSELOR_FROM_CAE';

export const GET_EACH_COUNSELOR_PROFILE = 'GET_EACH_COUNSELOR_PROFILE';
>>>>>>> Stashed changes
