export const GET_VISIT_SCHEDULE_CONTENT_ERROR = 'GET_VISIT_SCHEDULE_CONTENT_ERROR';

export const GET_VISIT_SCHEDULE_POST_LIST_ERROR = 'GET_VISIT_SCHEDULE_POST_LIST_ERROR';

export const GET_CURRENT_SCHEDULE_ERROR = 'GET_CURRENT_SCHEDULE_ERROR';

export const UPDATE_CURRENT_SCHEDULE_ERROR = 'UPDATE_CURRENT_SCHEDULE_ERROR';
