const foodStock = [
  { question: 'FS01', label: 'Escola não possui estoque de alimentos', markedYes: false, markedNo: false, status: false, key: 0 },
  { question: 'FS02', label: 'Alimentos vencidos', markedYes: false, markedNo: false, status: false, key: 1 },
  { question: 'FS03', label: 'Embalagens roídas', markedYes: false, markedNo: false, status: false, key: 2 },
  { question: 'FS04', label: 'Insetos dentro das embalagens', markedYes: false, markedNo: false, status: false, key: 3 },
  { question: 'FS05', label: 'Alimentos em contato com o chão', markedYes: false, markedNo: false, status: false, key: 4 },
  { question: 'FS06', label: 'Alimentos dentro de caixas', markedYes: false, markedNo: false, status: false, key: 5 },
  { question: 'FS07', label: 'Produtos de limpeza junto aos alimentos', markedYes: false, markedNo: false, status: false, key: 6 },
  { question: 'FS08', label: 'Embalagens abertas', markedYes: false, markedNo: false, status: false, key: 7 },
  { question: 'FS09', label: 'Prateleiras enferrujadas', markedYes: false, markedNo: false, status: false, key: 8 },
  { question: 'FS10', label: 'Prateleiras encostadas na parede', markedYes: false, markedNo: false, status: false, key: 9 },
  { question: 'FS11', label: 'Local abafado', markedYes: false, markedNo: false, status: false, key: 10 },
  { question: 'FS12', label: 'Contato direto dos raios de sol com as embalagens', markedYes: false, markedNo: false, status: false, key: 11 },
  { question: 'FS13', label: 'Falta de controle de entrada de alimentos', markedYes: false, markedNo: false, status: false, key: 12 },
  { question: 'FS14', label: 'Falta de controle de saída de alimentos', markedYes: false, markedNo: false, status: false, key: 13 },
  { question: 'FS15', label: 'Telhado sem forro', markedYes: false, markedNo: false, status: false, key: 14 },
  { question: 'FS16', label: 'Telhado com furos', markedYes: false, markedNo: false, status: false, key: 15 },
  { question: 'FS17', label: 'Congelador sem termômetro', markedYes: false, markedNo: false, status: false, key: 16 },
  { question: 'FS18', label: 'Lixeiras destampadas', markedYes: false, markedNo: false, status: false, key: 17 },
  { question: 'FS19', label: 'Chão difícil de limpar', markedYes: false, markedNo: false, status: false, key: 18 },
  { question: 'FS20', label: 'Parede difícil de limpar', markedYes: false, markedNo: false, status: false, key: 19 },
  { question: 'FS21', label: 'Janelas sem tela de proteção', markedYes: false, markedNo: false, status: false, key: 20 },
  { question: 'FS22', label: 'Portas sem tela de proteção', markedYes: false, markedNo: false, status: false, key: 21 },
  { question: 'FS23', label: 'Portas sem rodapé', markedYes: false, markedNo: false, status: false, key: 22 },
  { question: 'FS24', label: 'Insetos sobrevoando o local', markedYes: false, markedNo: false, status: false, key: 23 },
  { question: 'FS25', label: 'Animais com livre circulação', markedYes: false, markedNo: false, status: false, key: 24 },
  { question: 'FS26', label: 'Ventilador de teto empoeirado', markedYes: false, markedNo: false, status: false, key: 25 },
  { question: 'FS27', label: 'Equipamentos sujos', markedYes: false, markedNo: false, status: false, key: 26 },
  { question: 'FS28', label: 'Local mal iluminado', markedYes: false, markedNo: false, status: false, key: 27 },
  { question: 'FS29', label: 'Local sujo', markedYes: false, markedNo: false, status: false, key: 28 },
  { question: 'FS30', label: 'Objetos que não sejam alimentos', markedYes: false, markedNo: false, status: false, key: 29 },
  { question: 'FS31', label: 'Lixo não é armazenado em local fechado', markedYes: false, markedNo: false, status: false, key: 30 },
];

export default foodStock;
