const kitchen = [
  { question: 'KI01', label: 'Escola não possui cozinha', markedYes: false, markedNo: false, status: false, key: 0 },
  { question: 'KI02', label: 'Telhado sem forro', markedYes: false, markedNo: false, status: false, key: 1 },
  { question: 'KI03', label: 'Telhado com furos', markedYes: false, markedNo: false, status: false, key: 2 },
  { question: 'KI04', label: 'Congelador sem termômetro', markedYes: false, markedNo: false, status: false, key: 3 },
  { question: 'KI05', label: 'Lixeiras destampadas', markedYes: false, markedNo: false, status: false, key: 4 },
  { question: 'KI06', label: 'Chão difícil de limpar', markedYes: false, markedNo: false, status: false, key: 5 },
  { question: 'KI07', label: 'Parede difícil de limpar', markedYes: false, markedNo: false, status: false, key: 6 },
  { question: 'KI08', label: 'Janelas sem tela de pressão', markedYes: false, markedNo: false, status: false, key: 7 },
  { question: 'KI09', label: 'Portas sem tela de pressão', markedYes: false, markedNo: false, status: false, key: 8 },
  { question: 'KI10', label: 'Portas sem rodapé', markedYes: false, markedNo: false, status: false, key: 9 },
  { question: 'KI11', label: 'Insetos sobrevoando o local', markedYes: false, markedNo: false, status: false, key: 10 },
  { question: 'KI12', label: 'Animais', markedYes: false, markedNo: false, status: false, key: 11 },
  { question: 'KI13', label: 'Ventilador de teto empoeirado', markedYes: false, markedNo: false, status: false, key: 12 },
  { question: 'KI14', label: 'Equipamentos sujos', markedYes: false, markedNo: false, status: false, key: 13 },
  { question: 'KI15', label: 'Local mal iluminado', markedYes: false, markedNo: false, status: false, key: 14 },
  { question: 'KI16', label: 'Local sujo', markedYes: false, markedNo: false, status: false, key: 15 },
  { question: 'KI17', label: 'Lixo não é armazenado em local fechado', markedYes: false, markedNo: false, status: false, key: 16 },
  { question: 'KI18', label: 'Tamanho da cozinha é inadequado', markedYes: false, markedNo: false, status: false, key: 17 },
  { question: 'KI19', label: 'Ausência de planilha de rotina de higienização das instalações', markedYes: false, markedNo: false, status: false, key: 18 },
  { question: 'KI20', label: 'Produtos de higienização não regularizados pelo Ministério da Saúde', markedYes: false, markedNo: false, status: false, key: 19 },
  { question: 'KI21', label: 'Ausência de ralo sifonado com o sistema abre e fecha', markedYes: false, markedNo: false, status: false, key: 20 },
  { question: 'KI22', label: 'Instalações elétricas inadequadas', markedYes: false, markedNo: false, status: false, key: 21 },
  { question: 'KI23', label: 'Inexistência de lavatórios na área de manipulação com água corrente, em posições adequadas em relação ao fluxo de produção e serviço, e em número suficiente de modo a atender toda a área de produção', markedYes: false, markedNo: false, status: false, key: 22 },
  { question: 'KI24', label: 'A quantidade de equipamentos não é suficiente (geladeira, freezer, fogão, liquidificador, cortador de legumes, etc)', markedYes: false, markedNo: false, status: false, key: 23 },
  { question: 'KI25', label: 'A quantidade de utensílios não é suficiente (pratos, copos, talheres, panelas, conchas, facas, etc)', markedYes: false, markedNo: false, status: false, key: 24 },
];

export default kitchen;
