const foodStock = [
  { label: 'Escola não possui Estoque de Alimentos', marked: false, key: 0 },
  { label: 'Alimentos vencidos', marked: false, key: 1 },
  { label: 'Embalagens roídas', marked: false, key: 2 },
  { label: 'Insetos dentro das embalagens', marked: false, key: 3 },
  { label: 'Alimentos em contato com o chão', marked: false, key: 4 },
  { label: 'Alimentos dentro de caixas', marked: false, key: 5 },
  { label: 'Produtos de limpeza junto aos alimentos', marked: false, key: 6 },
  { label: 'Embalagens abertas', marked: false, key: 7 },
  { label: 'Prateleiras enferrujadas', marked: false, key: 8 },
  { label: 'Prateleiras encostadas na parede', marked: false, key: 9 },
  { label: 'Local abafado', marked: false, key: 10 },
  { label: 'Contato direto dos raios de sol com as embalagens', marked: false, key: 11 },
  { label: 'Falta de controle de entrada de alimentos', marked: false, key: 12 },
  { label: 'Falta de controle de saída de alimentos', marked: false, key: 13 },
  { label: 'Telhado sem forro', marked: false, key: 14 },
  { label: 'Telhado com furos', marked: false, key: 15 },
  { label: 'Congelador sem termômetro', marked: false, key: 16 },
  { label: 'Lixeiras destampadas', marked: false, key: 17 },
  { label: 'Chão difícil de limpar', marked: false, key: 18 },
  { label: 'Parede difícil de limpar', marked: false, key: 19 },
  { label: 'Janelas sem tela de proteção', marked: false, key: 20 },
  { label: 'Portas sem tela de proteção', marked: false, key: 21 },
  { label: 'Portas sem rodapé', marked: false, key: 22 },
  { label: 'Insetos sobrevoando o local', marked: false, key: 23 },
  { label: 'Animais com livre circulação', marked: false, key: 24 },
  { label: 'Ventilador de teto empoeirado', marked: false, key: 25 },
  { label: 'Equipamentos sujos', marked: false, key: 26 },
  { label: 'Local mal iluminado', marked: false, key: 27 },
  { label: 'Local sujo', marked: false, key: 28 },
  { label: 'Objetos que não sejam alimentos', marked: false, key: 29 },
  { label: 'Lixo não é armazenado em local fechado', marked: false, key: 30 },
];

export default foodStock;
