const foodStock = [
  { label: 'Escola possui Estoque de Alimentos', markedYes: false, markedNo: false, status: false, key: 0 },
  { label: 'Alimentos vencidos', markedYes: false, markedNo: false, status: false, key: 1 },
  { label: 'Embalagens roídas', markedYes: false, markedNo: false, status: false, key: 2 },
  { label: 'Insetos dentro das embalagens', markedYes: false, markedNo: false, status: false, key: 3 },
  { label: 'Alimentos em contato com o chão', markedYes: false, markedNo: false, status: false, key: 4 },
  { label: 'Alimentos dentro de caixas', markedYes: false, markedNo: false, status: false, key: 5 },
  { label: 'Produtos de limpeza junto aos alimentos', markedYes: false, markedNo: false, status: false, key: 6 },
  { label: 'Embalagens abertas', markedYes: false, markedNo: false, status: false, key: 7 },
  { label: 'Prateleiras enferrujadas', markedYes: false, markedNo: false, status: false, key: 8 },
  { label: 'Prateleiras encostadas na parede', markedYes: false, markedNo: false, status: false, key: 9 },
  { label: 'Local abafado', markedYes: false, markedNo: false, status: false, key: 10 },
  { label: 'Contato direto dos raios de sol com as embalagens', markedYes: false, markedNo: false, status: false, key: 11 },
  { label: 'Falta de controle de entrada de alimentos', markedYes: false, markedNo: false, status: false, key: 12 },
  { label: 'Falta de controle de saída de alimentos', markedYes: false, markedNo: false, status: false, key: 13 },
  { label: 'Telhado sem forro', markedYes: false, markedNo: false, status: false, key: 14 },
  { label: 'Telhado com furos', markedYes: false, markedNo: false, status: false, key: 15 },
  { label: 'Congelador sem termômetro', markedYes: false, markedNo: false, status: false, key: 16 },
  { label: 'Lixeiras destampadas', markedYes: false, markedNo: false, status: false, key: 17 },
  { label: 'Chão difícil de limpar', markedYes: false, markedNo: false, status: false, key: 18 },
  { label: 'Parede difícil de limpar', markedYes: false, markedNo: false, status: false, key: 19 },
  { label: 'Janelas sem tela de proteção', markedYes: false, markedNo: false, status: false, key: 20 },
  { label: 'Portas sem tela de proteção', markedYes: false, markedNo: false, status: false, key: 21 },
  { label: 'Portas sem rodapé', markedYes: false, markedNo: false, status: false, key: 22 },
  { label: 'Insetos sobrevoando o local', markedYes: false, markedNo: false, status: false, key: 23 },
  { label: 'Animais com livre circulação', markedYes: false, markedNo: false, status: false, key: 24 },
  { label: 'Ventilador de teto empoeirado', markedYes: false, markedNo: false, status: false, key: 25 },
  { label: 'Equipamentos sujos', markedYes: false, markedNo: false, status: false, key: 26 },
  { label: 'Local mal iluminado', markedYes: false, markedNo: false, status: false, key: 27 },
  { label: 'Local sujo', markedYes: false, markedNo: false, status: false, key: 28 },
  { label: 'Objetos que não sejam alimentos', markedYes: false, markedNo: false, status: false, key: 29 },
  { label: 'Lixo não é armazenado em local fechado', markedYes: false, markedNo: false, status: false, key: 30 },
];

export default foodStock;
