const foodStock = [
  { label: 'Escola não possui Estoque de Alimentos', status: 'naovisto', key: 0 },
  { label: 'Alimentos vencidos', status: 'naovisto', key: 1 },
  { label: 'Embalagens roídas', status: 'naovisto', key: 2 },
  { label: 'Insetos dentro das embalagens', status: 'naovisto', key: 3 },
  { label: 'Alimentos em contato com o chão', status: 'naovisto', key: 4 },
  { label: 'Alimentos dentro de caixas', status: 'naovisto', key: 5 },
  { label: 'Produtos de limpeza junto aos alimentos', status: 'naovisto', key: 6 },
  { label: 'Embalagens abertas', status: 'naovisto', key: 7 },
  { label: 'Prateleiras enferrujadas', status: 'naovisto', key: 8 },
  { label: 'Prateleiras encostadas na parede', status: 'naovisto', key: 9 },
  { label: 'Local abafado', status: 'naovisto', key: 10 },
  { label: 'Contato direto dos raios de sol com as embalagens', status: 'naovisto', key: 11 },
  { label: 'Falta de controle de entrada de alimentos', status: 'naovisto', key: 12 },
  { label: 'Falta de controle de saída de alimentos', status: 'naovisto', key: 13 },
  { label: 'Telhado sem forro', status: 'naovisto', key: 14 },
  { label: 'Telhado com furos', status: 'naovisto', key: 15 },
  { label: 'Congelador sem termômetro', status: 'naovisto', key: 16 },
  { label: 'Lixeiras destampadas', status: 'naovisto', key: 17 },
  { label: 'Chão difícil de limpar', status: 'naovisto', key: 18 },
  { label: 'Parede difícil de limpar', status: 'naovisto', key: 19 },
  { label: 'Janelas sem tela de proteção', status: 'naovisto', key: 20 },
  { label: 'Portas sem tela de proteção', status: 'naovisto', key: 21 },
  { label: 'Portas sem rodapé', status: 'naovisto', key: 22 },
  { label: 'Insetos sobrevoando o local', status: 'naovisto', key: 23 },
  { label: 'Animais com livre circulação', status: 'naovisto', key: 24 },
  { label: 'Ventilador de teto empoeirado', status: 'naovisto', key: 25 },
  { label: 'Equipamentos sujos', status: 'naovisto', key: 26 },
  { label: 'Local mal iluminado', status: 'naovisto', key: 27 },
  { label: 'Local sujo', status: 'naovisto', key: 28 },
  { label: 'Objetos que não sejam alimentos', status: 'naovisto', key: 29 },
  { label: 'Lixo não é armazenado em local fechado', status: 'naovisto', key: 30 },
];

export default foodStock;
