const kitchen = [
  { label: 'Escola possui Cozinha', markedYes: false, markedNo: false, status: false, key: 0 },
  { label: 'Merendeiras com esmalte nas unhas', markedYes: false, markedNo: false, status: false, key: 1 },
  { label: 'Merendeiras com unhas compridas', markedYes: false, markedNo: false, status: false, key: 2 },
  { label: 'Merendeiras doentes', markedYes: false, markedNo: false, status: false, key: 3 },
  { label: 'Merendeiras sem touca', markedYes: false, markedNo: false, status: false, key: 4 },
  { label: 'Merendeiras usando brincos, anéis ou pulseiras', markedYes: false, markedNo: false, status: false, key: 5 },
  { label: 'Visitantes/Merendeiras sem touca', markedYes: false, markedNo: false, status: false, key: 6 },
  { label: 'Telhado sem forro', markedYes: false, markedNo: false, status: false, key: 7 },
  { label: 'Telhado com furos', markedYes: false, markedNo: false, status: false, key: 8 },
  { label: 'Congelador sem termômetro', markedYes: false, markedNo: false, status: false, key: 9 },
  { label: 'Lixeiras destampadas', markedYes: false, markedNo: false, status: false, key: 10 },
  { label: 'Chão difícil de limpar', markedYes: false, markedNo: false, status: false, key: 11 },
  { label: 'Parede difícil de limpar', markedYes: false, markedNo: false, status: false, key: 12 },
  { label: 'Janelas sem tela de pressão', markedYes: false, markedNo: false, status: false, key: 13 },
  { label: 'Portas sem tela de pressão', markedYes: false, markedNo: false, status: false, key: 14 },
  { label: 'Portas sem rodapé', markedYes: false, markedNo: false, status: false, key: 15 },
  { label: 'Insetos sobrevoando o local', markedYes: false, markedNo: false, status: false, key: 16 },
  { label: 'Animais', markedYes: false, markedNo: false, status: false, key: 17 },
  { label: 'Ventilador de teto empoeirado', markedYes: false, markedNo: false, status: false, key: 18 },
  { label: 'Equipamentos sujos', markedYes: false, markedNo: false, status: false, key: 19 },
  { label: 'Local mal iluminado', markedYes: false, markedNo: false, status: false, key: 20 },
  { label: 'Local sujo', markedYes: false, markedNo: false, status: false, key: 21 },
  { label: 'Lixo não é armazenado em local fechado', markedYes: false, markedNo: false, status: false, key: 22 },
];

export default kitchen;
