const kitchen = [
  { label: 'Escola possui Cozinha', markedYes: false, markedNo: false, status: false, key: 0 },
  { label: 'Merendeiras com esmalte nas unhas', markedYes: false, markedNo: false, status: false, key: 1 },
  { label: 'Merendeiras com unhas compridas', markedYes: false, markedNo: false, status: false, key: 2 },
  { label: 'Merendeiras doentes', markedYes: false, markedNo: false, status: false, key: 3 },
  { label: 'Merendeiras sem touca', markedYes: false, markedNo: false, status: false, key: 4 },
  { label: 'Merendeiras usando brincos, anéis ou pulseiras', markedYes: false, markedNo: false, status: false, key: 5 },
  { label: 'Visitantes/Merendeiras sem touca', markedYes: false, markedNo: false, status: false, key: 6 },
  { label: 'Telhado sem forro', markedYes: false, markedNo: false, status: false, key: 7 },
  { label: 'Telhado com furos', markedYes: false, markedNo: false, status: false, key: 8 },
  { label: 'Congelador sem termômetro', markedYes: false, markedNo: false, status: false, key: 9 },
  { label: 'Lixeiras destampadas', markedYes: false, markedNo: false, status: false, key: 10 },
  { label: 'Chão difícil de limpar', markedYes: false, markedNo: false, status: false, key: 11 },
  { label: 'Parede difícil de limpar', markedYes: false, markedNo: false, status: false, key: 12 },
  { label: 'Janelas sem tela de pressão', markedYes: false, markedNo: false, status: false, key: 13 },
  { label: 'Portas sem tela de pressão', markedYes: false, markedNo: false, status: false, key: 14 },
  { label: 'Portas sem rodapé', markedYes: false, markedNo: false, status: false, key: 15 },
  { label: 'Insetos sobrevoando o local', markedYes: false, markedNo: false, status: false, key: 16 },
  { label: 'Animais', markedYes: false, markedNo: false, status: false, key: 17 },
  { label: 'Ventilador de teto empoeirado', markedYes: false, markedNo: false, status: false, key: 18 },
  { label: 'Equipamentos sujos', markedYes: false, markedNo: false, status: false, key: 19 },
  { label: 'Local mal iluminado', markedYes: false, markedNo: false, status: false, key: 20 },
  { label: 'Local sujo', markedYes: false, markedNo: false, status: false, key: 21 },
  { label: 'Lixo não é armazenado em local fechado', markedYes: false, markedNo: false, status: false, key: 22 },
  { label: 'Tamanho da cozinha é adequado', markedYes: false, markedNo: false, status: false, key: 23 },
  { label: 'Presença de planilha de rotina de higienização das instalações', markedYes: false, markedNo: false, status: false, key: 24 },
  { label: 'Produtos de higienização regularizados pelo Ministério da Saúde', markedYes: false, markedNo: false, status: false, key: 25 },
  { label: 'Presença de ralo sifonado com o sistema abre e fecha', markedYes: false, markedNo: false, status: false, key: 26 },
  { label: 'Instalações elétricas adequadas', markedYes: false, markedNo: false, status: false, key: 27 },
  { label: 'Existência de lavatórios na área de manipulação com água corrente, em posições adequadas em relação ao fluxo de produção e serviço, e em número suficiente de modo a atender toda a área de produção', markedYes: false, markedNo: false, status: false, key: 28 },
  { label: 'A quantidade de equipamentos é suficiente (geladeira, freezer, fogão, liquidificador, cortador de legumes, etc)', markedYes: false, markedNo: false, status: false, key: 29 },
  { label: 'A quantidade de utensílios é suficiente (pratos, copos, talheres, panelas, conchas, facas, etc)', markedYes: false, markedNo: false, status: false, key: 30 },
];

export default kitchen;
